table _Measures
	lineageTag: 397a008b-58f7-4d24-b4c7-ab8fb6859c59

	measure 'Is the data up to date?' =
			
			// This measure determines the header information which will be used in the dashboard. Displaying to the users of the dashboard if there is something wrong
			// Retrieves the latest refresh date
			VAR LatestRefreshDate =
			    MAX ( 'Last refresh'[Datum laatste verversing] ) // Gets the latest date out of the fact table, this assumes your fact table doesn't contain dates that are in the future.
			VAR LastDateInFct =
			    CALCULATE ( MAX ( DIM_date[Date] ), ALL ( DIM_date[Date] ) ) // Checks if the data is refreshed compared to the fact table
			VAR DataIsUpToDate =
			    IF ( LastDateInFct >= TODAY () - 1, "Yes", "No" ) // Checks if the dashboard is refreshed in the Power BI Service.
			VAR DashboardIsRefreshed =
			    IF ( LatestRefreshDate = TODAY (), "Yes", "No" ) // Final checks for the status
			VAR DashboardRefreshStatus =
			    SWITCH (
			        TRUE (),
			        DashboardIsRefreshed = "No", "⚠ Dashboard has problems with refreshing ⚠",
			        DataIsUpToDate = "No",
			            "⚠ Dashboard has refreshed, but there is some error with the data on the background ⚠",
			        DataIsUpToDate = "Yes", "Dashboard is up to date"
			    )
			RETURN
			    DashboardRefreshStatus
		formatString: #,0
		displayFolder: Technical measures for end-users
		lineageTag: 9f8aaa55-1638-4e78-a3f1-d77a957be221

	measure 'Total sellers' = DISTINCTCOUNT('FACT Sales'[Seller ID])
		formatString: 0
		lineageTag: 68d88367-9012-4d49-86b3-61b72d52af69

	measure 'Total GP' = SUM('FACT Sales'[Total gp])
		formatString: #,0.0
		lineageTag: cafcdacb-36ee-445e-816d-ddd48ffeddb6

	measure 'Total customers' = DISTINCTCOUNT('FACT Sales'[Customer Name])
		formatString: 0
		lineageTag: c50dca5b-f431-4d1f-a4e5-650093470cac

	measure 'Total orders' = COUNTROWS('FACT Sales')
		formatString: 0
		lineageTag: 2541fe9e-26b5-4126-ac1d-06820ec0fda5

	measure 'Total GP last month' = CALCULATE([Total GP], 'DIM Date'[Month Offset] = -1)
		lineageTag: 2bcd609f-fcba-4eb4-9a97-8bab6809afea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total GP month to date' = CALCULATE([Total GP], 'DIM Date'[Month Offset] = 0)
		lineageTag: b48b47cb-4262-4ac9-87a4-d5244845b802

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column1
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 654edbc1-1360-4061-becf-bd9a90ebe214
		summarizeBy: none
		sourceColumn: Column1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["UNNECESSARY_COLUMNS"]}

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["ENSURE_TABLES_HAVE_RELATIONSHIPS"]}

	annotation PBI_NavigationStepName = Navigation

